### ISSUE TITLE
从模板创建后，随便删几个组件，编译就失败。

### ISSUE THREAD

**Issue by wgf4242** [Tencent/cloudbase-framework#152]
**Bug 描述**
**Describe the bug**
比如汽车预约试驾，创建后编译通过。删除几个组件再撤销删除。
代码编辑器里添加
```
    console.log('---------> LifeCycle onPageReady')
    // const scene = decodeURIComponent(query.scene)
    // console.log(scene)
    // $page.dataset.state.testState = scene
    // this.setData({"id47": 213})
    // $page.widgets.id60.text='人员ID: ' + scene
    // $page.widgets.id60.value='1value'
```
本地编译就失败。

1.撤销添加的内容。恢复原始版本。也无法通过编译。

2.日志找不到，文件没有创建或者直接被删除了。

请简单清晰地描述您遇到的bug。
```
---------------- Install npm dependencies: 10909.765ms
 CloudBase Framework  info     low-code build fail: 1
 CloudBase Framework  error     undefined
 CloudBase Framework  info     部署日志: 'C:\\Users\\wgfab\\cloudbase-framework\\logs\\Wed Jan 13 2021 21:53:43 GMT+0800 (GMT+08:00).log'

[云开发低码] 低码应用构建失败 [ appId:app-xvw, buildId:1610546020424 ]
```

**Comment by binggg** [comment]
低代码应用么，收到，我们看下



---原始邮件---
发件人: "wgf4242"<notifications@github.com&gt;
发送时间: 2021年1月13日(周三) 晚上9:57
收件人: "Tencent/cloudbase-framework"<cloudbase-framework@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Tencent/cloudbase-framework] 从模板创建后，随便删几个组件，编译就失败。 (#152)




 
Bug 描述
 Describe the bug
 比如汽车预约试驾，创建后编译通过。删除几个组件再撤销删除。编译就失败。
 
日志找不到直接消失掉了。
 
请简单清晰地描述您遇到的bug。
 A clear and concise description of what the bug is.
 g.com/en/docs/cli/install for documentation about this command. ---------------- Install npm dependencies: 10909.765ms  CloudBase Framework  info     low-code build fail: 1  CloudBase Framework  error     undefined  CloudBase Framework  info     部署日志: 'C:\\Users\\wgfab\\cloudbase-framework\\logs\\Wed Jan 13 2021 21:53:43 GMT+0800 (GMT+08:00).log' [云开发低码] 低码应用构建失败 [ appId:app-xvw, buildId:1610546020424 ]  
重现步骤
 To Reproduce
 
重现 bug 的步骤：
  
打开 '...' 

点击 '...' 

看到报错信息 
 
Steps to reproduce the behavior:
  
Go to '...' 

Click on '....' 

Scroll down to '....' 

See error 
 
预期的行为
 Expected behavior
 请简单明了地描述您期望的行为。
 A clear and concise description of what you expected to happen.
 
截图
 Screenshots
 如果方便的话，可以提交截图来帮助我们分析您遇到的问题
 If applicable, add screenshots to help explain your problem.
 
错误日志
 Debug LOG
 
请使用 --verbose 参数来打印 debug 日志信息，然后将命令行输出复制在这里
 
例如 cloudbase framework deploy --verbose
 
其他上下文信息
 Additional context
 
Add any other context about the problem here.

**Comment by wgf4242** [comment]
试了下，这个名字  21:53:43 有冒号。。建不了log。格式化处理下。

**Comment by binggg** [comment]
@wgf4242 好的，感谢反馈

**Comment by lt5c** [comment]
可以加一下低码QQ群 1003059706

然后在群里反馈一下，我们这边才好联系到你查问题。

**Comment by binggg** [comment]
已经拉群沟通
